recipes = [
    {
        "author_credit":"https://www.allrecipes.com/recipe/8489941/roast-chicken-with-grapefruit/",
        "calories": 226,
        "carbs": 22,
        "category": "Chicken",
        "description": "Bacon, grapefruit, and a flambéed sauce turn a basic roast chicken into a holiday homerun in under two hours.",
        "fat": 13,
        "image":"https://www.allrecipes.com/thmb/i_nKZDHXWG41mXHoYb6pHhMmluc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Roast-Chicken-with-Grapefruit-4x3-1-f969245d84214699ba208c4fb215a54c.jpg",
        "ingredients": "3 ruby red grapefruit, 1 tablespoon kosher salt,1.5 teaspoons freshly ground black pepper,1 (4 pound) whole chicken,3 slices thick-cut bacon,1 tablespoon olive oil,1 tablespoon Cognac or brandy,2 tablespoons low-sodium chicken broth,1 teaspoon half-and-half or cream",
        "instructions":"Working over a bowl to collect juice, section grapefruits into suprêmes, cutting away all peel, pith, and membranes. Squeeze remaining skin and membranes into the bowl to extract as much juice as possible.|Preheat the oven to 375 degrees F (190 degrees C).|Stir together salt and pepper in a small bowl. Slip fingers beneath the skin of the chicken breast and thighs to loosen it from the meat. Rub salt mixture under skin, inside cavity, and over skin. Tuck half the suprêmes and a few parsley sprigs into chicken cavity. Transfer chicken, breast side up, to a rack in a baking dish or a cast-iron skillet.|Tie legs together with kitchen twine; fold wing tips back and tuck under chicken. Halve bacon; drape over breast in a herringbone pattern, overlapping as needed. Drizzle with oil, coating any uncovered skin.|Roast in the preheated oven for 40 minutes. Pour grapefruit juice over chicken. Continue roasting 35 to 40 minutes or until an instant-read thermometer inserted into thickest parts of thigh and breast registers 170°F. Tent with foil; let rest at least 15 minutes. Discard kitchen twine. Remove and reserve suprêmes from chicken cavity.|For sauce, warm cognac in a small stainless-steel or copper (not nonstick) skillet over medium heat for a few seconds until shimmering at the edges. Remove from heat.|Carefully ignite with a stick lighter or long match. Let burn for 1 minute. Add roasted grapefruit suprêmes, the broth, and half-and-half; heat through. Season to taste with salt and pepper.|Serve chicken on a platter with remaining fresh suprêmes (or extra grapefruit wedges) and parsley sprigs. Spoon warm sauce over carved chicken.",
        "protein": 4,
        "servings": 4,
        "shopping_list": "3 grapefruit produce,0.001 box-of-salt spice,0.01 black-pepper spice,1 whole-chicken meat,0.25 package-bacon meat,0.01 liter-oil dry-good,0.025 bottle-Conac dry-good,0.1 liter-chicken-broth dry-good,0.25 quart-of-cream dairy",
        "title": "Roast Chicken with Grapefruit",
        "time": "1 hour 50 minutes",
    },
    # {
    #     "author_credit":"",
    #     "calories": 0,
    #     "carbs": 0,
    #     "category": "",
    #     "description": "",
    #     "fat": 0,
    #     "image":".jpg",
    #     "ingredients":"",
    #     "instructions":"",
    #     "protein": 0,
    #     "servings": 0,
    #     "shopping_list":"ingredient amount sale_volume" ,
    #     "time": 0,
    #     "title": "",
    # },
    {
        "author_credit":"https://www.allrecipes.com/recipe/26317/chicken-pot-pie-ix/",
        "calories": 421,
        "carbs": 30,
        "category": "Chicken",
        "description": "A delicious chicken pie made from scratch with carrots, peas, and celery in a pre-made crust. Add thyme and poultry seasoning for more flavor.",
        "fat": 24,
        "image":"https://www.allrecipes.com/thmb/by58FX0CztxRq6gg_rjfPnjyuZo=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/26317-chicken-pot-pie-mfs-480-7e84da80505a410fa75139eab67a652f.jpg",
        "ingredients":"1 pound skinless, boneless chicken breast halves - cubed,1 cup sliced carrots,1 cup frozen green peas,½ cup sliced celery,⅓ cup butter,⅓ cup chopped onion,⅓ cup all-purpose flour,½ teaspoon salt,¼ teaspoon black-pepper,¼ teaspoon celery seed,1 ¾ cups chicken broth,⅔ cup milk,2 (9 inch) unbaked pie crusts",
        "instructions":"Preheat the oven to 425 degrees F (220 degrees C.)|Combine chicken, carrots, peas, and celery in a saucepan; add water to cover and bring to a boil. Boil for 15 minutes, then remove from the heat and drain.|While the chicken is cooking, melt butter in another saucepan over medium heat. Add onion and cook until soft and translucent, 5 to 7 minutes. Stir in flour, salt, pepper, and celery seed. Slowly stir in chicken broth and milk. Reduce heat to medium-low and simmer until thick, 5 to 10 minutes. Remove from heat and set aside.|Place chicken and vegetables in the bottom pie crust. Pour hot liquid mixture over top. Cover with top crust, seal the edges, and cut away any excess dough. Make several small slits in the top crust to allow steam to escape.|Bake in the preheated oven until pastry is golden brown and filling is bubbly, 30 to 35 minutes. Cool for 10 minutes before serving.",
        "protein": 18,
        "servings": 8,
        "shopping_list":"1 pound(s)-chicken-breast meat,0.25 lb-carrots produce,0.25 bag-frozen-peas frozen,0.2 lb-celery produce,.25 lb-butter dairy,0.33 onion produce,0.1 lb-all-purpose-flour dry-good,0.001 lb-salt spice,0.01 black-pepper spice,0.01 celery-seed spice,0.66 liter-chicken-broth dry-good,0.07 gallon-milk dairy,2 pie-crust frozen",
        "time": "1 hour 20 minutes",
        "title": "Chicken Pot Pie",
    },
    {
        "author_credit":"https://www.allrecipes.com/recipe/212721/indian-chicken-curry-murgh-kari/",

        "calories": 470,

        "carbs": 15,

        "category": "Chicken",

        "description": "Murgh Kari makes use of a potent spice blend that includes garam masala, coriander, turmeric, and cayenne pepper. Tomato, yogurt, and onion are also essential ingredients in this classic Indian main dish. Fresh minced garlic and ginger lend a pleasant sharpness.",

        "fat": 24,

        "image":"https://www.allrecipes.com/thmb/TzSL6HwKmnUlGR7nUioU9va23TM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/212721-indian-chicken-curry-murgh-kari-john-w-e7d6b6866ff7405387d1061ef16ab5aa.jpg",

        "ingredients":"2 pounds skinless, boneless chicken breast halves,2 teaspoons salt,½ cup cooking oil,1 ½ cups chopped onion,1 tablespoon minced garlic,1 ½ teaspoons minced fresh ginger root,1 tablespoon curry powder,1 teaspoon ground cumin,1 teaspoon ground turmeric,1 teaspoon ground coriander,1 teaspoon cayenne pepper,1 tablespoon water,1 (15 ounce) can crushed tomatoes,1 cup plain yogurt,1 tablespoon chopped fresh cilantro,1 teaspoon salt,½ cup water,1 teaspoon garam masala,1 tablespoon chopped fresh cilantro,1 tablespoon fresh lemon juice",

        "instructions":"Sprinkle the chicken breasts with 2 teaspoons salt.|Heat oil in a large skillet over high heat; partially cook the chicken in the hot oil in batches until completely browned on all sides. Transfer browned chicken breasts to a plate and set aside.|Reduce the heat to medium and add onion, garlic, and ginger to the oil remaining in the skillet. Cook and stir until onion turns soft and translucent, 5 to 8 minutes. Stir curry powder, cumin, turmeric, coriander, cayenne, and 1 tablespoon of water into the onion mixture; allow to heat together for about 1 minute while stirring. Add tomatoes, yogurt, 1 tablespoon chopped cilantro, and 1 teaspoon salt to the mixture; stir to combine.|Return chicken breast to the skillet along with any juices on the plate. Pour in 1/2 cup water and bring to a boil, turning the chicken to coat with the sauce. Sprinkle garam masala and 1 tablespoon cilantro over the chicken.,Cover the skillet and simmer until chicken breasts are no longer pink in the center and the juices run clear, about 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C). Drizzle with lemon juice to serve.",

        "protein": 38,

        "servings": 6,

        "shopping_list":"2 pound(s)-chicken-breast meat,0.001 lb-salt spices,0.2 liter-oil dry-good,0.2 bulb-garlic produce,2 oz-ginger-root produce,0.1 8oz-curry-powder spice,0.1 8oz-ground-cumin spice,0.1 8oz-ground-tumeric spice,0.01 8oz-ground-coriander spice,0.25 quart-plain-yogurt dairy,0.25 bunch-cilantro produce,0.5 lemon produce" ,


        "time": "1 hour",   
        "title": "Indian Chicken Curry (Murgh Kari)",
    },    
    {
        "author_credit":"https://www.allrecipes.com/recipe/8499/basic-chicken-salad/",
        "calories":779,
        "carbs": 8,
        "category": "Chicken",
        "description": "This basic chicken salad is the best and a family favorite. I like to use baked thighs or breasts that have been sprinkled with basil or rosemary.",
        "fat": 63,
        "image":"https://www.allrecipes.com/thmb/Sh1cbkK3lbzyKxoovX7gt8xNQiw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8499-Basic-Chicken-Salad-04_1x1-01a227e11703424cb84025f8e26f1a03.jpg",
        "ingredients":"½ cup blanched slivered almonds,½ cup mayonnaise,1 tablespoon lemon juice,¼ teaspoon ground black pepper,2 cups chopped, cooked chicken meat,1 stalk celery, chopped",
        "instructions":"Place almonds in a frying pan. Toast over medium-high heat, shaking frequently. Watch carefully, as they burn easily.|Mix together mayonnaise, lemon juice, and pepper in a medium bowl. Toss with chicken, toasted almonds, and celery.",
        "protein": 44,
        "servings": 2,
        "shopping_list":"0.2 lb-almonds produce,0.1 mayonnaise dry-good,0.5 lemon produce,0.001 black-pepper spice,0.2 lb-celery produce,1 lb-chicken-breast meat" ,
        "time": "10 minutes",
        "title": "Best Chicken Salad",
    },    
        {
        "author_credit":"https://www.allrecipes.com/recipe/21659/chicken-quesadillas/",
        "calories": 472,
        "carbs": 40,
        "category": "Chicken",
        "description": "This chicken quesadilla recipe is great to make for parties. Zesty chicken, cooked peppers, and melted cheese are a delightful combination. Cut into wedges and serve with sour cream and salsa.",
        "fat": 22,
        "image":"https://www.allrecipes.com/thmb/RSXrMkCrpz6tNmu2kL2owFtp9EM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Chicken-Quesadillas-1x1-1-2000-8b4750792f6e4ac4a26b31cc9c152a84.jpg",
        "ingredients":"1 pound skinless, boneless chicken breast, diced,1 (1.27 ounce) packet fajita seasoning,1 tablespoon vegetable oil,2 green bell peppers, chopped,2 red bell peppers, chopped,1 onion, chopped,10 (10 inch) flour tortillas,1 (8 ounce) package shredded Cheddar cheese,1 (8 ounce) package shredded Monterey Jack cheese",
        "instructions":"Preheat the broiler. Lightly grease a baking sheet.|Toss chicken with fajita seasoning, then spread onto the prepared baking sheet. Place under the broiler and cook until chicken is cooked through and no longer pink in the center, about 5 minutes.|Preheat the oven to 350 degrees F (175 degrees C).|Heat oil in a large saucepan over medium heat. Stir in bell peppers, onion, and broiled chicken. Cook and stir until vegetables have softened, about 10 minutes.|Layer half of each tortilla with chicken and vegetable mixture, Cheddar cheese, Monterey Jack cheese, and bacon bits. Fold tortillas in half and place onto a baking sheet.|Bake quesadillas in the preheated oven until cheeses have melted, about 10 minutes. Cut each quesadilla into wedges and serve.",
        "protein": 28,
        "servings": 10,
        "shopping_list":"1 lb-chicken-breast meat,1 packet-fajita-seasoning spice,2 red-bell-pepper produce,2 green-bell-pepper produce,1 onion produce,1 10-pack-flour-tortilla dry-good,1 (8oz)-package-shredded-cheddar-cheese dairy,1 (8oz)-package-shredded-montery-jack-cheese dairy" ,
        "time": "45 minutes",
        "title": "Chicken Quesadillas",
    },
     
        {
        "author_credit":"https://www.allrecipes.com/recipe/220128/chef-johns-buttermilk-fried-chicken/",
        "calories": 1262,
        "carbs": 56,
        "category": "Chicken",
        "description": "Buttermilk fried chicken that's incredibly tender, thanks to tangy buttermilk. After the buttermilk soak, dredge the chicken pieces in seasoned flour and fry them in hot oil until crisp and golden.",
        "fat": 85,
        "image":"https://www.allrecipes.com/thmb/ld9qzOC1fBr81Ipeg8sI3SvlDWc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/3548106-chef-johns-buttermilk-fried-chicken-CHEF-JOHN-1x1-1-564e58d7b77e4aaa8330aa7ce8734676.jpg",
        "ingredients":"1 (3 1/2) pound chicken, cut into 8 pieces,1 teaspoon black pepper,2 teaspoon salt,1½  teaspoon paprika,1 teaspoon white pepper,¼ teaspoon dried rosemary,¼ teaspoon ground thyme,¼ teaspoon dried oregano,¼ teaspoon dried sage,1 teaspoon cayenne pepper,2 cups buttermilk,2 cups flour,½ teaspoon garlic powder,½ teaspoon onion powder,2 ½ quarts peanut oil for frying",
        "instructions":"Toss chicken pieces, black pepper, salt, paprika, white pepper, rosemary, thyme, oregano, sage, and cayenne together in a large bowl.|Stir in buttermilk until chicken is evenly coated. Cover and refrigerate for 6 hours.|Combine flour, salt, paprika, cayenne, garlic powder, white pepper, and onion powder in a large shallow dish.|Remove chicken from buttermilk and dredge each piece in seasoned flour; shake off any excess and transfer to a plate.|Heat peanut oil in a large Dutch oven to 350 degrees F (175 degrees C).|Add chicken pieces to the hot oil and fry for 10 minutes. Turn chicken pieces and fry for another 10 to15 minutes.|Transfer fried chicken to a cooling rack set over a paper towel-lined baking sheet. Let sit for 10 minutes before serving.|Chefs Note: The oil is 350 degrees F (175 degrees C) to start, but it may drop to about 300 degrees (150 degrees C) when chicken is added. It should rise back to 305 to 310 degrees F (155 degrees C) and be held at that temperature until done, about 25 minutes.",
        "protein": 66,
        "servings": 4,
        "shopping_list":"2.5 quarts-peanut-oil dry-good,1 whole-chicken meat,0.01 black-pepper spice,0.01 paprika spice,0.04 lb-salt spice,0.01 white-pepper spice,0.02 dried-rosemary spice,0.01 dried-thyme spice,0.5 quart(s)-buttermilk dairy,0.2 lb-all-purpose-flour dry-good,0.01 garlic-powder spice, 0.01 onion-powder spice, 0.01 dried-oregano spice, 0.01 dried-sage spice, 0.01 cayenne-pepper spice" ,
        "time": "6 hours 10 minutes",
        "title": "Chef John's Buttermilk Fried Chicken",
    },
        {
        "author_credit":"https://www.allrecipes.com/recipe/51283/maple-salmon/",
        "calories": 265,
        "carbs": 14,
        "category": "Seafood",
        "description": "This maple glazed salmon is delicious and very easy to prepare. I love maple syrup in everything and decided to use it in the marinade. My husband totally loved it; he wasn't a salmon fan until now.",
        "fat": 12,
        "image":"https://www.allrecipes.com/thmb/jaXQ9LIKIDQ1w9I8eJa4Xm_eZoE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/862371-cd7a4b6c481f444382e3f69273b982f9.jpg",
        "ingredients":"¼ cup maple syrup,2 tablespoons soy sauce,1 clove garlic, minced,¼ teaspoon garlic powder,⅛ teaspoon ground black pepper,1 pound salmon",
        "instructions":"Stir maple syrup, soy sauce, garlic, garlic salt, and pepper together in a small bowl.|Cut salmon into 4 equal-sized fillets; place in a shallow glass baking dish and coat with maple syrup mixture. Cover the dish and marinate salmon in the refrigerator for 30 minutes, turning once halfway.|Preheat the oven to 400 degrees F (200 degrees C).|Place the baking dish in the preheated oven and bake salmon uncovered until flesh easily flakes with a fork, about 20 minutes.",
        "protein": 23,
        "servings": 4,
        "shopping_list":"1 lb-salmon meat,0.05 bottle-soysauce dry-good,0.0125 quart-mayple-syrup dry-good,0.125 bulb-garlic produce,0.001 black-pepper spice,0.001 garlic-powder spice" ,
        "time": '1 hour',
        "title": "Maple Salmon",
    },
        {
        "author_credit":"https://www.allrecipes.com/recipe/72508/the-best-vegetarian-chili-in-the-world/",
        "calories": 0,
        "carbs": 0,
        "category": "Vegetarian",
        "description": "This spicy vegetarian chili is ready in no time and packed with vegetables, beans, and flavor! Break out your soup pot and fix up a batch of this delicious chili — it tastes even better the next day.",
        "fat": 0,
        "image":".jpg",
        "ingredients":"",
        "instructions":"",
        "protein": 0,
        "servings": 0,
        #TODO"shopping_list":"",
        "time": 0,
        "title": "The Best Vegetarian Chili in the World",
    },
        # {
    #     "author_credit":"",
    #     "calories": 0,
    #     "carbs": 0,
    #     "category": "",
    #     "description": "",
    #     "fat": 0,
    #     "image":".jpg",
    #     "ingredients":"",
    #     "instructions":"",
    #     "protein": 0,
    #     "servings": 0,
    #     "shopping_list":"ingredient amount sale_volume" ,
    #     "time": 0,
    #     "title": "",
    # },



]