recipes = [
    {
        "author_credit":'https://www.allrecipes.com/recipe/8489941/roast-chicken-with-grapefruit/',
        "calories": 226,
        "carbs": 22,
        "fat": 13,
        "image":"https://www.allrecipes.com/thmb/i_nKZDHXWG41mXHoYb6pHhMmluc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Roast-Chicken-with-Grapefruit-4x3-1-f969245d84214699ba208c4fb215a54c.jpg",
        "ingredients": "3 ruby red grapefruit, 1 tablespoon kosher salt,1.5 teaspoons freshly ground black pepper,1 (4 pound) whole chicken,3 slices thick-cut bacon,1 tablespoon olive oil,1 tablespoon Cognac or brandy,2 tablespoons low-sodium chicken broth,1 teaspoon half-and-half or cream",
        "instructions":'Working over a bowl to collect juice, section grapefruits into suprêmes, cutting away all peel, pith, and membranes. Squeeze remaining skin and membranes into the bowl to extract as much juice as possible.|Preheat the oven to 375 degrees F (190 degrees C).|Stir together salt and pepper in a small bowl. Slip fingers beneath the skin of the chicken breast and thighs to loosen it from the meat. Rub salt mixture under skin, inside cavity, and over skin. Tuck half the suprêmes and a few parsley sprigs into chicken cavity. Transfer chicken, breast side up, to a rack in a baking dish or a cast-iron skillet.|Tie legs together with kitchen twine; fold wing tips back and tuck under chicken. Halve bacon; drape over breast in a herringbone pattern, overlapping as needed. Drizzle with oil, coating any uncovered skin.|Roast in the preheated oven for 40 minutes. Pour grapefruit juice over chicken. Continue roasting 35 to 40 minutes or until an instant-read thermometer inserted into thickest parts of thigh and breast registers 170°F. Tent with foil; let rest at least 15 minutes. Discard kitchen twine. Remove and reserve suprêmes from chicken cavity.|For sauce, warm cognac in a small stainless-steel or copper (not nonstick) skillet over medium heat for a few seconds until shimmering at the edges. Remove from heat.|Carefully ignite with a stick lighter or long match. Let burn for 1 minute. Add roasted grapefruit suprêmes, the broth, and half-and-half; heat through. Season to taste with salt and pepper.|Serve chicken on a platter with remaining fresh suprêmes (or extra grapefruit wedges) and parsley sprigs. Spoon warm sauce over carved chicken.',
        "protein": 4,
        "shopping_list": "",
        "title": '',
    },
        {
        "author_credit":'authorName',
        "calories": 0,
        "fat": 0,
        "image":".jpg",
        "ingredients":[[]],
        "instructions":'',
        "protein": 0,
        "shopping_list":[["ingredient amount sale_volume" ]],
        "title": '',
    },
        {
        "author_credit":'authorName',
        "calories": 0,
        "fat": 0,
        "image":".jpg",
        "ingredients":[[]],
        "instructions":'',
        "protein": 0,
        "shopping_list":[["ingredient amount sale_volume" ]],
        "title": '',
    },
        {
        "author_credit":'authorName',
        "calories": 0,
        "fat": 0,
        "image":".jpg",
        "ingredients":[[]],
        "instructions":'',
        "protein": 0,
        "shopping_list":[["ingredient amount sale_volume" ]],
        "title": '',
    },
        {
        "author_credit":'authorName',
        "calories": 0,
        "fat": 0,
        "image":".jpg",
        "ingredients":[[]],
        "instructions":'',
        "protein": 0,
        "shopping_list":[["ingredient amount sale_volume" ]],
        "title": '',
    }
]